version: '2'
services:

  server:
    image: ${IMAGE_SERVER_DEMO}
    ports:
      - 8056:8056
    container_name: server-api

  test:
    image: ${IMAGE_TEST}
    volumes:
      - ../application:/application
    depends_on:
       - server
    command: "/tmp/wait-for-it.sh server:8056 -t 50 -- /tmp/runtest.sh"
