version: '2'
services:

  server:
    image: ${IMAGE_SERVER_DEMO}
    ports:
      - 8056:8056
    container_name: server-api

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbproject
    container_name: test-mysql

  test:
    image: ${IMAGE_TEST}
    volumes:
      - ../application:/application
    depends_on:
       - mysql
       - server
    command: "/tmp/wait-for-it.sh mysql:3306 -t 50 -- /tmp/runtest.sh"
